
version: 2.1

command:
  print_pipeline_id:
    parameters:
      id:
        type: string

    steps:
      - run: echo << parameters.id >>

jobs:
  say_hello:
    docker:
      - image: circleci/node:13.8.0.
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

workflows:
  my_job:
    jobs:
      - say_hello