# version: 2.1

# command:
#   print_pipeline_id:
#     steps:
#       - run: echo ${CIRCLE_WORKFLOW_ID}

# jobs:
#   my_job:
#     docker:
#       - image: cimg/base:2022.05
#     steps:
#       - print_pipeline_id

# workflows:
#   my_workflow:
#     jobs:
#       - my_job

version: 2.1

command:
  print_pipeline_id:
    parameters:
      id:
        type: string

    steps:
      - run: echo << parameters.id >>

jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

workflows:
  my_job:
    jobs:
      - say_hello